RED="\e[31m"

echo -e "${RED}Horas   Lunes	  Martes     Miercoles	    Jueves      Viernes"
echo "8:15	Lengua	  Lengua     E.F.	    Valen	Ingles"
echo "9:10 	Valen	  Dibujo     Ingles	    Tutoria     E.F."
echo "10:05	Fisica	  Valen	     Dibujo	    Mates	Dibujo"
echo "11:00   _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-"
echo "11:25 	E.F.	  Fisica     Filo	    E.F.	Historia"
echo "12:20	Dibujo    Historia   Mates	    Fisica	Fisica"
echo "13:15   _-_-_-_-_-_-_-_-_-   Historia	    Filo	Lengua"
echo "13:30	Mates	  Mates"
echo "14:25	Filo	  Ingles"
